"""
Guardrail Schemas

Request/response models for guardrail definitions and configurations.

Guardrails are atomic security checks that can be attached to entities
via policies. Each guardrail has:
- A type (e.g., "pii_ssn", "rbac", "rate_limit_per_minute")
- A display name and description
- A category (rbac, pii, content, rate_limit)
- A default configuration
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.config.constants import (
    GuardrailCategory,
    GuardrailType,
    ScanDirection,
    Severity,
)
from app.schemas.common import BaseSchema


# =============================================================================
# GUARDRAIL EVENT (for audit logging)
# =============================================================================


class GuardrailEvent(BaseModel):
    """Event generated by guardrail evaluation."""

    guardrail_type: str
    triggered: bool
    action_taken: str
    details: dict[str, Any] = Field(default_factory=dict)
    severity: Severity = Severity.INFO


# =============================================================================
# GUARDRAIL DEFINITION SCHEMAS
# =============================================================================


class GuardrailDefinitionBase(BaseModel):
    """Base guardrail definition fields."""

    guardrail_type: GuardrailType = Field(..., description="Unique guardrail type identifier")
    display_name: str = Field(..., min_length=1, max_length=100, description="Display name")
    description: str | None = Field(None, max_length=500)
    category: GuardrailCategory = Field(..., description="Guardrail category")


class GuardrailDefinitionCreate(BaseModel):
    """Schema for creating a guardrail definition (admin only).

    If display_name, description, or default_config are not provided,
    they will be auto-filled from GUARDRAIL_METADATA and GUARDRAIL_DEFAULTS.
    """

    guardrail_type: GuardrailType = Field(..., description="Unique guardrail type identifier")
    display_name: str | None = Field(
        None,
        min_length=1,
        max_length=100,
        description="Display name (auto-filled from metadata if not provided)",
    )
    description: str | None = Field(
        None,
        max_length=500,
        description="Description (auto-filled from metadata if not provided)",
    )
    category: GuardrailCategory = Field(..., description="Guardrail category")
    default_config: dict[str, Any] = Field(
        default_factory=dict,
        description="Default configuration (auto-filled from defaults if not provided)",
    )
    is_active: bool = Field(default=True)


class GuardrailDefinitionUpdate(BaseModel):
    """Schema for updating a guardrail definition (admin only)."""

    display_name: str | None = Field(None, min_length=1, max_length=100)
    description: str | None = Field(None, max_length=500)
    default_config: dict[str, Any] | None = None
    is_active: bool | None = None


class GuardrailDefinitionResponse(BaseSchema):
    """Schema for guardrail definition response."""

    id: str
    guardrail_type: GuardrailType
    display_name: str
    description: str | None
    category: GuardrailCategory
    default_config: dict[str, Any]
    is_active: bool
    created_at: datetime
    updated_at: datetime


class GuardrailDefinitionListResponse(BaseModel):
    """Schema for listing guardrail definitions."""

    guardrails: list[GuardrailDefinitionResponse]
    total: int


# =============================================================================
# GUARDRAIL CONFIGURATION SCHEMAS (per guardrail type)
# =============================================================================


class RBACConfig(BaseModel):
    """RBAC guardrail configuration."""

    default_action: str = Field(
        default="deny",
        description="Default action when no rule matches: 'allow' or 'deny'",
    )
    allowed_tools: list[str] = Field(
        default_factory=list,
        description="List of allowed tools/patterns (supports wildcards)",
    )
    denied_tools: list[str] = Field(
        default_factory=list,
        description="List of denied tools/patterns (supports wildcards)",
    )


class PIIConfig(BaseModel):
    """PII detection guardrail configuration (applies to all PII types)."""

    direction: ScanDirection = Field(
        default=ScanDirection.BOTH,
        description="Which direction to scan",
    )
    redaction_pattern: str = Field(
        default="[REDACTED]",
        description="Pattern for redaction replacement",
    )


class ContentConfig(BaseModel):
    """Content filter guardrail configuration."""

    direction: ScanDirection = Field(
        default=ScanDirection.BOTH,
        description="Which direction to scan",
    )
    max_chars: int | None = Field(
        None,
        ge=0,
        description="Maximum characters (for large documents)",
    )
    max_rows: int | None = Field(
        None,
        ge=0,
        description="Maximum rows (for structured data)",
    )


class RateLimitConfig(BaseModel):
    """Rate limit guardrail configuration."""

    limit: int = Field(
        ...,
        ge=1,
        description="Maximum requests per time window",
    )


# =============================================================================
# GENERIC GUARDRAIL CONFIG (used in policies)
# =============================================================================


class GuardrailPolicyConfig(BaseModel):
    """Generic guardrail configuration for a policy.

    The specific fields depend on the guardrail type.
    This is stored in the policy's `config` field.
    """

    # Common fields
    direction: ScanDirection | None = Field(
        None,
        description="Direction to apply guardrail (for PII/content)",
    )

    # RBAC specific
    default_action: str | None = Field(None, description="RBAC default action")
    allowed_tools: list[str] | None = Field(None, description="RBAC allowed tools")
    denied_tools: list[str] | None = Field(None, description="RBAC denied tools")

    # PII specific
    redaction_pattern: str | None = Field(None, description="PII redaction pattern")

    # Content specific
    max_chars: int | None = Field(None, description="Content max characters")
    max_rows: int | None = Field(None, description="Content max rows")

    # Rate limit specific
    limit: int | None = Field(None, description="Rate limit value")

    class Config:
        """Pydantic config."""

        extra = "allow"  # Allow additional fields for flexibility
