# pylint: skip-file
"""initial_schema

Revision ID: 7ec179615239
Revises:
Create Date: 2025-12-19 12:05:19.150537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ec179615239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guardrail_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrails_category'), 'guardrails', ['category'], unique=False)
    op.create_index(op.f('ix_guardrails_guardrail_type'), 'guardrails', ['guardrail_type'], unique=True)
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_organisations_slug', 'organisations', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('mcp_server_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mcp_server_url', sa.String(length=500), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mcp_server_workspaces_org_deleted', 'mcp_server_workspaces', ['organisation_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_mcp_server_workspaces_organisation_id'), 'mcp_server_workspaces', ['organisation_id'], unique=False)
    op.create_index('uq_mcp_server_workspaces_org_slug', 'mcp_server_workspaces', ['organisation_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_org_deleted', 'users', ['organisation_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index('uq_users_org_email', 'users', ['organisation_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_users_super_admin_email', 'users', ['email'], unique=True, postgresql_where=sa.text('organisation_id IS NULL AND deleted_at IS NULL'))
    op.create_table('agent_accesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_workspace_id'], ['mcp_server_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_accesses_key_hash'), 'agent_accesses', ['key_hash'], unique=True)
    op.create_index(op.f('ix_agent_accesses_mcp_server_workspace_id'), 'agent_accesses', ['mcp_server_workspace_id'], unique=False)
    op.create_index('ix_agent_accesses_workspace_status', 'agent_accesses', ['mcp_server_workspace_id', 'is_active', 'is_revoked'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_workspace_id', sa.UUID(), nullable=True),
    sa.Column('agent_access_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.String(length=500), nullable=False),
    sa.Column('guardrail_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_workspace_id'], ['mcp_server_workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_agent_access_id'), 'audit_logs', ['agent_access_id'], unique=False)
    op.create_index('ix_audit_logs_agent_created', 'audit_logs', ['agent_access_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_agent_name'), 'audit_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_decision'), 'audit_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_audit_logs_mcp_server_workspace_id'), 'audit_logs', ['mcp_server_workspace_id'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organisation_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_org_decision', 'audit_logs', ['organisation_id', 'decision', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tool_name'), 'audit_logs', ['tool_name'], unique=False)
    op.create_index('ix_audit_logs_workspace_created', 'audit_logs', ['mcp_server_workspace_id', 'created_at'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_workspace_id', sa.UUID(), nullable=True),
    sa.Column('agent_access_id', sa.UUID(), nullable=True),
    sa.Column('guardrail_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_access_id'], ['agent_accesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_workspace_id'], ['mcp_server_workspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_agent_access_id'), 'policies', ['agent_access_id'], unique=False)
    op.create_index('ix_policies_effective_lookup', 'policies', ['organisation_id', 'deleted_at', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_policies_guardrail_id'), 'policies', ['guardrail_id'], unique=False)
    op.create_index(op.f('ix_policies_mcp_server_workspace_id'), 'policies', ['mcp_server_workspace_id'], unique=False)
    op.create_index(op.f('ix_policies_organisation_id'), 'policies', ['organisation_id'], unique=False)
    op.create_index('ix_policies_workspace_lookup', 'policies', ['mcp_server_workspace_id', 'deleted_at'], unique=False)
    op.create_index('uq_policy_guardrail_per_scope', 'policies', ['organisation_id', 'mcp_server_workspace_id', 'agent_access_id', 'guardrail_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_policy_guardrail_per_scope', table_name='policies', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_policies_workspace_lookup', table_name='policies')
    op.drop_index(op.f('ix_policies_organisation_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_mcp_server_workspace_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_guardrail_id'), table_name='policies')
    op.drop_index('ix_policies_effective_lookup', table_name='policies')
    op.drop_index(op.f('ix_policies_agent_access_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_audit_logs_workspace_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tool_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_decision', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_mcp_server_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_decision'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_name'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_agent_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_agent_access_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agent_accesses_workspace_status', table_name='agent_accesses')
    op.drop_index(op.f('ix_agent_accesses_mcp_server_workspace_id'), table_name='agent_accesses')
    op.drop_index(op.f('ix_agent_accesses_key_hash'), table_name='agent_accesses')
    op.drop_table('agent_accesses')
    op.drop_index('uq_users_super_admin_email', table_name='users', postgresql_where=sa.text('organisation_id IS NULL AND deleted_at IS NULL'))
    op.drop_index('uq_users_org_email', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index('ix_users_org_deleted', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_mcp_server_workspaces_org_slug', table_name='mcp_server_workspaces', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_mcp_server_workspaces_organisation_id'), table_name='mcp_server_workspaces')
    op.drop_index('ix_mcp_server_workspaces_org_deleted', table_name='mcp_server_workspaces')
    op.drop_table('mcp_server_workspaces')
    op.drop_index('uq_organisations_slug', table_name='organisations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('organisations')
    op.drop_index(op.f('ix_guardrails_guardrail_type'), table_name='guardrails')
    op.drop_index(op.f('ix_guardrails_category'), table_name='guardrails')
    op.drop_table('guardrails')
    # ### end Alembic commands ###

